### ISSUE TITLE
[REPL] Can't use packages that start with an @

### ISSUE THREAD

**Issue by moklick** [sveltejs/sites#490]
Hey! 

It seems that it is not possible to use package names that start with an "@" in the package name. 
Reproduction REPL: https://svelte.dev/repl/880b7422926642a59a483aaf6c8ccd3e?version=3.59.1 

Is this a known issue or is the REPL not made to work with third party packages? I would assume that it's very common to have a package name like this since npm introduced organizations.

**Comment by Conduitry** [comment]
The issue isn't that the package name begins with `@`. The error message about `Unexpected character '@'` refers to the `@` inside that package's `index.css`.

The REPL does support package names beginning with a `@`, but it does not support importing CSS files as though they were JS files. Because of the REPL's simple nature, I don't think it's likely to support that in the future. There are other solutions out there - like StackBlitz - that give you a complete development environment and build pipeline in a browser.

**Comment by moklick** [comment]
Got it. Thanks for the info.
