### ISSUE TITLE
Nav menu does not display current page when on docs

### ISSUE THREAD

**Issue by geoffrich** [sveltejs/sites#52]
On the SvelteKit site, the current page is displayed in the nav menu. For example, this is the homepage:

![image](https://user-images.githubusercontent.com/4992896/130850407-a4e4f147-4c16-440c-b941-2c88b04cde05.png)

However, on the other pages (e.g. docs, faq, migrating) the current page is not displayed in the menu and the caret is off center:

![image](https://user-images.githubusercontent.com/4992896/130850473-f545a425-99ba-48c5-b24f-724433d5dc1f.png)

There's also no indication around the current page when the menu is open:

![image](https://user-images.githubusercontent.com/4992896/130850633-04f80a2d-f6c6-4de3-a617-34858bf16d4e.png)

I feel like this was working at one point, but it's not working now.

Tested on Chrome/Firefox on Windows 10 and on iOS Safari.

**Comment by Rich-Harris** [comment]
Closing this as the design has changed somewhat since this issue. I opened https://github.com/sveltejs/sites/pull/193, which doesn't make the current section visible when the menu is closed (I don't think there's room for it, in the general case) but highlights the current section when the menu is visible or we're using the desktop layout
